http:
  host: '0.0.0.0'
  port: '8000'

postgres:
  name: 'go_fj'
  password: 'DTCZffXxtzksTc77m0jRPxrdLD3RaV8C'
  max_cons: 50
  host: 'dpg-cltdhqla73kc73eh8k30-a'
  port: 'frankfurt-postgres.render.com'
  conn_timeout: 10